var searchData=
[
  ['radiusresultset',['RadiusResultSet',['../d2/d69/classcvflann_1_1RadiusResultSet.html',1,'cvflann']]],
  ['radiusuniqueresultset',['RadiusUniqueResultSet',['../d8/d4a/classcvflann_1_1RadiusUniqueResultSet.html',1,'cvflann']]],
  ['range',['Range',['../da/d35/classcv_1_1Range.html',1,'cv']]],
  ['rebind',['rebind',['../da/d52/classcv_1_1Allocator_1_1rebind.html',1,'cv::Allocator']]],
  ['rect',['Rect',['../d3/d22/classcv_1_1gapi_1_1own_1_1Rect.html',1,'cv::gapi::own']]],
  ['rect',['Rect',['../d6/d30/structcv_1_1gapi_1_1wip_1_1draw_1_1Rect.html',1,'cv::gapi::wip::draw']]],
  ['rect_5f',['Rect_',['../d2/d44/classcv_1_1Rect__.html',1,'cv']]],
  ['regionlayer',['RegionLayer',['../d1/d21/classcv_1_1dnn_1_1RegionLayer.html',1,'cv::dnn']]],
  ['relu6layer',['ReLU6Layer',['../dc/dcd/classcv_1_1dnn_1_1ReLU6Layer.html',1,'cv::dnn']]],
  ['relulayer',['ReLULayer',['../dd/df0/classcv_1_1dnn_1_1ReLULayer.html',1,'cv::dnn']]],
  ['reorglayer',['ReorgLayer',['../d6/da3/classcv_1_1dnn_1_1ReorgLayer.html',1,'cv::dnn']]],
  ['reshapelayer',['ReshapeLayer',['../db/d15/classcv_1_1dnn_1_1ReshapeLayer.html',1,'cv::dnn']]],
  ['resizelayer',['ResizeLayer',['../db/d38/classcv_1_1dnn_1_1ResizeLayer.html',1,'cv::dnn']]],
  ['resultset',['ResultSet',['../d8/d42/classcvflann_1_1ResultSet.html',1,'cvflann']]],
  ['rng',['RNG',['../d1/dd6/classcv_1_1RNG.html',1,'cv']]],
  ['rng_5fmt19937',['RNG_MT19937',['../db/d3e/classcv_1_1RNG__MT19937.html',1,'cv']]],
  ['rnnlayer',['RNNLayer',['../dd/dfd/classcv_1_1dnn_1_1RNNLayer.html',1,'cv::dnn']]],
  ['rotatedrect',['RotatedRect',['../db/dd6/classcv_1_1RotatedRect.html',1,'cv']]],
  ['rotationwarper',['RotationWarper',['../da/db8/classcv_1_1detail_1_1RotationWarper.html',1,'cv::detail']]],
  ['rotationwarperbase',['RotationWarperBase',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20compressedrectilinearportraitprojector_20_3e',['RotationWarperBase&lt; CompressedRectilinearPortraitProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20compressedrectilinearprojector_20_3e',['RotationWarperBase&lt; CompressedRectilinearProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20cylindricalportraitprojector_20_3e',['RotationWarperBase&lt; CylindricalPortraitProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20cylindricalprojector_20_3e',['RotationWarperBase&lt; CylindricalProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20fisheyeprojector_20_3e',['RotationWarperBase&lt; FisheyeProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20mercatorprojector_20_3e',['RotationWarperBase&lt; MercatorProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20paniniportraitprojector_20_3e',['RotationWarperBase&lt; PaniniPortraitProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20paniniprojector_20_3e',['RotationWarperBase&lt; PaniniProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20planeportraitprojector_20_3e',['RotationWarperBase&lt; PlanePortraitProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20planeprojector_20_3e',['RotationWarperBase&lt; PlaneProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20sphericalportraitprojector_20_3e',['RotationWarperBase&lt; SphericalPortraitProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20sphericalprojector_20_3e',['RotationWarperBase&lt; SphericalProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20stereographicprojector_20_3e',['RotationWarperBase&lt; StereographicProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20transversemercatorprojector_20_3e',['RotationWarperBase&lt; TransverseMercatorProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rtrees',['RTrees',['../d0/d65/classcv_1_1ml_1_1RTrees.html',1,'cv::ml']]]
];
