var searchData=
[
  ['cache',['Cache',['../da/da5/structcv_1_1gapi_1_1fluid_1_1View_1_1Cache.html',1,'cv::gapi::fluid::View']]],
  ['cache',['Cache',['../dc/dd8/structcv_1_1gapi_1_1fluid_1_1Buffer_1_1Cache.html',1,'cv::gapi::fluid::Buffer']]],
  ['calibratecrf',['CalibrateCRF',['../dd/de3/classcv_1_1CalibrateCRF.html',1,'cv']]],
  ['calibratedebevec',['CalibrateDebevec',['../da/d27/classcv_1_1CalibrateDebevec.html',1,'cv']]],
  ['calibraterobertson',['CalibrateRobertson',['../d3/d30/classcv_1_1CalibrateRobertson.html',1,'cv']]],
  ['call_5fand_5fpostprocess',['call_and_postprocess',['../df/de6/structcv_1_1detail_1_1OCVCallHelper_3_01Impl_00_01std_1_1tuple_3_01Ins_8_8_8_01_4_00_01std_1_1tu8bfb77c34485398698447f60ee067830.html',1,'cv::detail::OCVCallHelper&lt; Impl, std::tuple&lt; Ins... &gt;, std::tuple&lt; Outs... &gt; &gt;']]],
  ['call_5fand_5fpostprocess',['call_and_postprocess',['../d5/def/structcv_1_1detail_1_1OCLCallHelper_3_01Impl_00_01std_1_1tuple_3_01Ins_8_8_8_01_4_00_01std_1_1tua67cc2fc13da93c8cd58afcdf4d9cddf.html',1,'cv::detail::OCLCallHelper&lt; Impl, std::tuple&lt; Ins... &gt;, std::tuple&lt; Outs... &gt; &gt;']]],
  ['callback',['Callback',['../d8/d9f/classcv_1_1LMSolver_1_1Callback.html',1,'cv::LMSolver']]],
  ['cameraparams',['CameraParams',['../d4/d0a/structcv_1_1detail_1_1CameraParams.html',1,'cv::detail']]],
  ['cascadeclassifier',['CascadeClassifier',['../d1/de5/classcv_1_1CascadeClassifier.html',1,'cv']]],
  ['channelscompensator',['ChannelsCompensator',['../d4/ddd/classcv_1_1detail_1_1ChannelsCompensator.html',1,'cv::detail']]],
  ['channelsprelulayer',['ChannelsPReLULayer',['../d7/de9/classcv_1_1dnn_1_1ChannelsPReLULayer.html',1,'cv::dnn']]],
  ['check',['check',['../dd/d16/classcv_1_1detail_1_1has__custom__wrap_1_1check.html',1,'cv::detail::has_custom_wrap']]],
  ['chisquaredistance',['ChiSquareDistance',['../dd/dd8/structcvflann_1_1ChiSquareDistance.html',1,'cvflann']]],
  ['choose_5fpolicy',['choose_policy',['../d5/da1/structcvflann_1_1anyimpl_1_1choose__policy.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20any_20_3e',['choose_policy&lt; any &gt;',['../d5/d51/structcvflann_1_1anyimpl_1_1choose__policy_3_01any_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20bool_20_3e',['choose_policy&lt; bool &gt;',['../d9/d10/structcvflann_1_1anyimpl_1_1choose__policy_3_01bool_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20float_20_3e',['choose_policy&lt; float &gt;',['../d2/d87/structcvflann_1_1anyimpl_1_1choose__policy_3_01float_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20signed_20char_20_3e',['choose_policy&lt; signed char &gt;',['../dc/d84/structcvflann_1_1anyimpl_1_1choose__policy_3_01signed_01char_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20signed_20long_20_3e',['choose_policy&lt; signed long &gt;',['../d7/d22/structcvflann_1_1anyimpl_1_1choose__policy_3_01signed_01long_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20signed_20short_20_3e',['choose_policy&lt; signed short &gt;',['../d3/d4a/structcvflann_1_1anyimpl_1_1choose__policy_3_01signed_01short_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20unsigned_20char_20_3e',['choose_policy&lt; unsigned char &gt;',['../dd/dd1/structcvflann_1_1anyimpl_1_1choose__policy_3_01unsigned_01char_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20unsigned_20long_20_3e',['choose_policy&lt; unsigned long &gt;',['../d9/dcd/structcvflann_1_1anyimpl_1_1choose__policy_3_01unsigned_01long_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20unsigned_20short_20_3e',['choose_policy&lt; unsigned short &gt;',['../d9/dd6/structcvflann_1_1anyimpl_1_1choose__policy_3_01unsigned_01short_01_4.html',1,'cvflann::anyimpl']]],
  ['circle',['Circle',['../d8/d07/structcv_1_1gapi_1_1wip_1_1draw_1_1Circle.html',1,'cv::gapi::wip::draw']]],
  ['circlesgridfinderparameters',['CirclesGridFinderParameters',['../d2/dd1/structcv_1_1CirclesGridFinderParameters.html',1,'cv']]],
  ['clahe',['CLAHE',['../d6/db6/classcv_1_1CLAHE.html',1,'cv']]],
  ['classificationmodel',['ClassificationModel',['../d0/dd5/classcv_1_1dnn_1_1ClassificationModel.html',1,'cv::dnn']]],
  ['commandlineparser',['CommandLineParser',['../d0/d2e/classcv_1_1CommandLineParser.html',1,'cv']]],
  ['comparet',['CompareT',['../d2/d76/structcvflann_1_1Heap_1_1CompareT.html',1,'cvflann::Heap']]],
  ['compileargtag',['CompileArgTag',['../dd/d3d/structcv_1_1detail_1_1CompileArgTag.html',1,'cv::detail']]],
  ['compileargtag_3c_20cv_3a_3agapi_3a_3agkernelpackage_20_3e',['CompileArgTag&lt; cv::gapi::GKernelPackage &gt;',['../d5/d58/structcv_1_1detail_1_1CompileArgTag_3_01cv_1_1gapi_1_1GKernelPackage_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20cv_3a_3agapi_3a_3agnetpackage_20_3e',['CompileArgTag&lt; cv::gapi::GNetPackage &gt;',['../dc/dbf/structcv_1_1detail_1_1CompileArgTag_3_01cv_1_1gapi_1_1GNetPackage_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20cv_3a_3agapi_3a_3ause_5fonly_20_3e',['CompileArgTag&lt; cv::gapi::use_only &gt;',['../df/d53/structcv_1_1detail_1_1CompileArgTag_3_01cv_1_1gapi_1_1use__only_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20cv_3a_3agraph_5fdump_5fpath_20_3e',['CompileArgTag&lt; cv::graph_dump_path &gt;',['../d3/d64/structcv_1_1detail_1_1CompileArgTag_3_01cv_1_1graph__dump__path_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20gfluidoutputrois_20_3e',['CompileArgTag&lt; GFluidOutputRois &gt;',['../d7/d5e/structcv_1_1detail_1_1CompileArgTag_3_01GFluidOutputRois_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20gfluidparallelfor_20_3e',['CompileArgTag&lt; GFluidParallelFor &gt;',['../de/d5f/structcv_1_1detail_1_1CompileArgTag_3_01GFluidParallelFor_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20gfluidparalleloutputrois_20_3e',['CompileArgTag&lt; GFluidParallelOutputRois &gt;',['../d5/dc7/structcv_1_1detail_1_1CompileArgTag_3_01GFluidParallelOutputRois_01_4.html',1,'cv::detail']]],
  ['complex',['Complex',['../da/df6/classcv_1_1Complex.html',1,'cv']]],
  ['compositeindex',['CompositeIndex',['../dc/d59/classcvflann_1_1CompositeIndex.html',1,'cvflann']]],
  ['compositeindexparams',['CompositeIndexParams',['../db/d3f/structcvflann_1_1CompositeIndexParams.html',1,'cvflann']]],
  ['compositeindexparams',['CompositeIndexParams',['../d5/d94/structcv_1_1flann_1_1CompositeIndexParams.html',1,'cv::flann']]],
  ['compressedrectilinearportraitprojector',['CompressedRectilinearPortraitProjector',['../d0/ded/structcv_1_1detail_1_1CompressedRectilinearPortraitProjector.html',1,'cv::detail']]],
  ['compressedrectilinearportraitwarper',['CompressedRectilinearPortraitWarper',['../dd/dc8/classcv_1_1detail_1_1CompressedRectilinearPortraitWarper.html',1,'cv::detail']]],
  ['compressedrectilinearportraitwarper',['CompressedRectilinearPortraitWarper',['../de/d9a/classcv_1_1CompressedRectilinearPortraitWarper.html',1,'cv']]],
  ['compressedrectilinearprojector',['CompressedRectilinearProjector',['../db/dbb/structcv_1_1detail_1_1CompressedRectilinearProjector.html',1,'cv::detail']]],
  ['compressedrectilinearwarper',['CompressedRectilinearWarper',['../dd/dbe/classcv_1_1detail_1_1CompressedRectilinearWarper.html',1,'cv::detail']]],
  ['compressedrectilinearwarper',['CompressedRectilinearWarper',['../d0/dd5/classcv_1_1CompressedRectilinearWarper.html',1,'cv']]],
  ['concatlayer',['ConcatLayer',['../da/d5c/classcv_1_1dnn_1_1ConcatLayer.html',1,'cv::dnn']]],
  ['conjgradsolver',['ConjGradSolver',['../d0/d21/classcv_1_1ConjGradSolver.html',1,'cv']]],
  ['constlayer',['ConstLayer',['../de/dff/classcv_1_1dnn_1_1ConstLayer.html',1,'cv::dnn']]],
  ['context',['Context',['../d1/d45/classcv_1_1ocl_1_1Context.html',1,'cv::ocl']]],
  ['convolutionlayer',['ConvolutionLayer',['../d5/dcf/classcv_1_1dnn_1_1ConvolutionLayer.html',1,'cv::dnn']]],
  ['creatornotfound',['CreatorNotFound',['../db/d35/classcvflann_1_1CreatorNotFound.html',1,'cvflann']]],
  ['cropandresizelayer',['CropAndResizeLayer',['../d8/d53/classcv_1_1dnn_1_1CropAndResizeLayer.html',1,'cv::dnn']]],
  ['croplayer',['CropLayer',['../d7/d86/classcv_1_1dnn_1_1CropLayer.html',1,'cv::dnn']]],
  ['cv16suf',['Cv16suf',['../dd/d0f/unionCv16suf.html',1,'']]],
  ['cv32suf',['Cv32suf',['../d9/df3/unionCv32suf.html',1,'']]],
  ['cv64suf',['Cv64suf',['../de/d55/unionCv64suf.html',1,'']]],
  ['cv_5ffinal',['CV_FINAL',['../da/dbd/structcvflann_1_1anyimpl_1_1CV__FINAL.html',1,'cvflann::anyimpl']]],
  ['cvabstractcamera',['CvAbstractCamera',['../d0/de8/interfaceCvAbstractCamera.html',1,'']]],
  ['cvhaldft',['cvhalDFT',['../de/d27/structcvhalDFT.html',1,'']]],
  ['cvhalfilter2d',['cvhalFilter2D',['../d2/da8/structcvhalFilter2D.html',1,'']]],
  ['cvhalkeypoint',['cvhalKeyPoint',['../d9/daa/structcvhalKeyPoint.html',1,'']]],
  ['cvphotocamera',['CvPhotoCamera',['../d4/d1d/interfaceCvPhotoCamera.html',1,'']]],
  ['cvphotocameradelegate_2dp',['CvPhotoCameraDelegate-p',['../d9/d97/protocolCvPhotoCameraDelegate-p.html',1,'']]],
  ['cvtype',['CvType',['../d1/def/structcv_1_1flann_1_1CvType.html',1,'cv::flann']]],
  ['cvtype_3c_20char_20_3e',['CvType&lt; char &gt;',['../dc/d89/structcv_1_1flann_1_1CvType_3_01char_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20double_20_3e',['CvType&lt; double &gt;',['../dc/d69/structcv_1_1flann_1_1CvType_3_01double_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20float_20_3e',['CvType&lt; float &gt;',['../dc/dd6/structcv_1_1flann_1_1CvType_3_01float_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20short_20_3e',['CvType&lt; short &gt;',['../d2/def/structcv_1_1flann_1_1CvType_3_01short_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20unsigned_20char_20_3e',['CvType&lt; unsigned char &gt;',['../d7/da5/structcv_1_1flann_1_1CvType_3_01unsigned_01char_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20unsigned_20short_20_3e',['CvType&lt; unsigned short &gt;',['../d9/d57/structcv_1_1flann_1_1CvType_3_01unsigned_01short_01_4.html',1,'cv::flann']]],
  ['cvvideocamera',['CvVideoCamera',['../db/da9/interfaceCvVideoCamera.html',1,'']]],
  ['cvvideocameradelegate_2dp',['CvVideoCameraDelegate-p',['../db/dbd/protocolCvVideoCameraDelegate-p.html',1,'']]],
  ['cylindricalportraitprojector',['CylindricalPortraitProjector',['../df/d3f/structcv_1_1detail_1_1CylindricalPortraitProjector.html',1,'cv::detail']]],
  ['cylindricalportraitwarper',['CylindricalPortraitWarper',['../dd/d19/classcv_1_1detail_1_1CylindricalPortraitWarper.html',1,'cv::detail']]],
  ['cylindricalprojector',['CylindricalProjector',['../dd/d96/structcv_1_1detail_1_1CylindricalProjector.html',1,'cv::detail']]],
  ['cylindricalwarper',['CylindricalWarper',['../d7/df6/classcv_1_1CylindricalWarper.html',1,'cv']]],
  ['cylindricalwarper',['CylindricalWarper',['../d3/dd6/classcv_1_1detail_1_1CylindricalWarper.html',1,'cv::detail']]],
  ['cylindricalwarpergpu',['CylindricalWarperGpu',['../d9/dbd/classcv_1_1detail_1_1CylindricalWarperGpu.html',1,'cv::detail']]]
];
