var searchData=
[
  ['kalmanfilter',['KalmanFilter',['../dd/d6a/classcv_1_1KalmanFilter.html',1,'cv']]],
  ['kaze',['KAZE',['../d3/d61/classcv_1_1KAZE.html',1,'cv']]],
  ['kdtreeindex',['KDTreeIndex',['../df/d36/classcvflann_1_1KDTreeIndex.html',1,'cvflann']]],
  ['kdtreeindexparams',['KDTreeIndexParams',['../d7/d99/structcvflann_1_1KDTreeIndexParams.html',1,'cvflann']]],
  ['kdtreeindexparams',['KDTreeIndexParams',['../d0/d99/structcv_1_1flann_1_1KDTreeIndexParams.html',1,'cv::flann']]],
  ['kdtreesingleindex',['KDTreeSingleIndex',['../db/d92/classcvflann_1_1KDTreeSingleIndex.html',1,'cvflann']]],
  ['kdtreesingleindexparams',['KDTreeSingleIndexParams',['../d5/d2d/structcvflann_1_1KDTreeSingleIndexParams.html',1,'cvflann']]],
  ['kernel',['Kernel',['../dd/d4c/classcv_1_1ocl_1_1Kernel.html',1,'cv::ocl']]],
  ['kernel',['Kernel',['../d7/db8/classcv_1_1ml_1_1SVM_1_1Kernel.html',1,'cv::ml::SVM']]],
  ['kernelarg',['KernelArg',['../d3/d17/classcv_1_1ocl_1_1KernelArg.html',1,'cv::ocl']]],
  ['kerneltag',['KernelTag',['../d4/d88/structcv_1_1detail_1_1KernelTag.html',1,'cv::detail']]],
  ['kerneltypemedium',['KernelTypeMedium',['../d9/d05/structcv_1_1detail_1_1KernelTypeMedium.html',1,'cv::detail']]],
  ['kerneltypemedium_3c_20ginfer_3c_20net_20_3e_2c_20net_3a_3aapi_20_3e',['KernelTypeMedium&lt; GInfer&lt; Net &gt;, Net::API &gt;',['../d9/d05/structcv_1_1detail_1_1KernelTypeMedium.html',1,'cv::detail']]],
  ['kerneltypemedium_3c_20ginferlist_3c_20net_20_3e_2c_20net_3a_3aapilist_20_3e',['KernelTypeMedium&lt; GInferList&lt; Net &gt;, Net::APIList &gt;',['../d9/d05/structcv_1_1detail_1_1KernelTypeMedium.html',1,'cv::detail']]],
  ['kerneltypemedium_3c_20k_2c_20std_3a_3afunction_3c_20r_28args_2e_2e_2e_29_3e_20_3e',['KernelTypeMedium&lt; K, std::function&lt; R(Args...)&gt; &gt;',['../dd/d28/structcv_1_1detail_1_1KernelTypeMedium_3_01K_00_01std_1_1function_3_01R_07Args_8_8_8_08_4_01_4.html',1,'cv::detail']]],
  ['kerneltypemedium_3c_20k_2c_20std_3a_3afunction_3c_20std_3a_3atuple_3c_20r_2e_2e_2e_20_3e_28args_2e_2e_2e_29_3e_20_3e',['KernelTypeMedium&lt; K, std::function&lt; std::tuple&lt; R... &gt;(Args...)&gt; &gt;',['../d5/d9a/structcv_1_1detail_1_1KernelTypeMedium_3_01K_00_01std_1_1function_3_01std_1_1tuple_3_01R_8_8_8_01_4_07Args_8_8_8_08_4_01_4.html',1,'cv::detail']]],
  ['keypoint',['KeyPoint',['../d2/d29/classcv_1_1KeyPoint.html',1,'cv']]],
  ['keypointsfilter',['KeyPointsFilter',['../de/db2/classcv_1_1KeyPointsFilter.html',1,'cv']]],
  ['kl_5fdivergence',['KL_Divergence',['../d2/dc2/structcvflann_1_1KL__Divergence.html',1,'cvflann']]],
  ['kmeansdistancecomputer',['KMeansDistanceComputer',['../d7/d6e/classcvflann_1_1KMeansIndex_1_1KMeansDistanceComputer.html',1,'cvflann::KMeansIndex']]],
  ['kmeansindex',['KMeansIndex',['../df/d1f/classcvflann_1_1KMeansIndex.html',1,'cvflann']]],
  ['kmeansindexparams',['KMeansIndexParams',['../df/d7a/structcv_1_1flann_1_1KMeansIndexParams.html',1,'cv::flann']]],
  ['kmeansindexparams',['KMeansIndexParams',['../de/dff/structcvflann_1_1KMeansIndexParams.html',1,'cvflann']]],
  ['knearest',['KNearest',['../dd/de1/classcv_1_1ml_1_1KNearest.html',1,'cv::ml']]],
  ['knnradiusuniqueresultset',['KNNRadiusUniqueResultSet',['../d3/dd8/classcvflann_1_1KNNRadiusUniqueResultSet.html',1,'cvflann']]],
  ['knnresultset',['KNNResultSet',['../d5/db2/classcvflann_1_1KNNResultSet.html',1,'cvflann']]],
  ['knnsimpleresultset',['KNNSimpleResultSet',['../d8/daa/classcvflann_1_1KNNSimpleResultSet.html',1,'cvflann']]],
  ['knnuniqueresultset',['KNNUniqueResultSet',['../d0/d5d/classcvflann_1_1KNNUniqueResultSet.html',1,'cvflann']]]
];
