var searchData=
[
  ['savedindexparams',['SavedIndexParams',['../dc/d2a/structcvflann_1_1SavedIndexParams.html',1,'cvflann']]],
  ['savedindexparams',['SavedIndexParams',['../de/de8/structcv_1_1flann_1_1SavedIndexParams.html',1,'cv::flann']]],
  ['scalar',['Scalar',['../d8/d72/classcv_1_1gapi_1_1own_1_1Scalar.html',1,'cv::gapi::own']]],
  ['scalar_5f',['Scalar_',['../d1/da0/classcv_1_1Scalar__.html',1,'cv']]],
  ['scalar_5f_3c_20double_20_3e',['Scalar_&lt; double &gt;',['../d1/da0/classcv_1_1Scalar__.html',1,'cv']]],
  ['scalar_5fwrapper',['scalar_wrapper',['../d2/d64/structcv_1_1detail_1_1scalar__wrapper.html',1,'cv::detail']]],
  ['scalar_5fwrapper_5focl',['scalar_wrapper_ocl',['../d2/d3a/structcv_1_1detail_1_1scalar__wrapper__ocl.html',1,'cv::detail']]],
  ['scalelayer',['ScaleLayer',['../dd/dde/classcv_1_1dnn_1_1ScaleLayer.html',1,'cv::dnn']]],
  ['scratch_5fhelper',['scratch_helper',['../db/df4/structcv_1_1detail_1_1scratch__helper.html',1,'cv::detail']]],
  ['scratch_5fhelper_3c_20false_2c_20impl_2c_20ins_2e_2e_2e_20_3e',['scratch_helper&lt; false, Impl, Ins... &gt;',['../d0/d94/structcv_1_1detail_1_1scratch__helper_3_01false_00_01Impl_00_01Ins_8_8_8_01_4.html',1,'cv::detail']]],
  ['scratch_5fhelper_3c_20true_2c_20impl_2c_20ins_2e_2e_2e_20_3e',['scratch_helper&lt; true, Impl, Ins... &gt;',['../dd/d8e/structcv_1_1detail_1_1scratch__helper_3_01true_00_01Impl_00_01Ins_8_8_8_01_4.html',1,'cv::detail']]],
  ['seamfinder',['SeamFinder',['../d7/d09/classcv_1_1detail_1_1SeamFinder.html',1,'cv::detail']]],
  ['searchparams',['SearchParams',['../d6/d59/structcvflann_1_1SearchParams.html',1,'cvflann']]],
  ['searchparams',['SearchParams',['../d5/d03/structcv_1_1flann_1_1SearchParams.html',1,'cv::flann']]],
  ['segmentationmodel',['SegmentationModel',['../da/dce/classcv_1_1dnn_1_1SegmentationModel.html',1,'cv::dnn']]],
  ['shared_5flock_5fguard',['shared_lock_guard',['../d9/d7f/classcv_1_1utils_1_1shared__lock__guard.html',1,'cv::utils']]],
  ['shiftlayer',['ShiftLayer',['../d3/dd8/classcv_1_1dnn_1_1ShiftLayer.html',1,'cv::dnn']]],
  ['shufflechannellayer',['ShuffleChannelLayer',['../de/d24/classcv_1_1dnn_1_1ShuffleChannelLayer.html',1,'cv::dnn']]],
  ['sigmoidlayer',['SigmoidLayer',['../dc/d09/classcv_1_1dnn_1_1SigmoidLayer.html',1,'cv::dnn']]],
  ['similarrects',['SimilarRects',['../d1/d65/classcv_1_1SimilarRects.html',1,'cv']]],
  ['simpleblobdetector',['SimpleBlobDetector',['../d0/d7a/classcv_1_1SimpleBlobDetector.html',1,'cv']]],
  ['simpledistance',['simpleDistance',['../d9/d12/structcvflann_1_1simpleDistance.html',1,'cvflann']]],
  ['simpledistance_3c_20chisquaredistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; ChiSquareDistance&lt; ElementType &gt;, ElementType &gt;',['../dd/d95/structcvflann_1_1simpleDistance_3_01ChiSquareDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20hellingerdistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; HellingerDistance&lt; ElementType &gt;, ElementType &gt;',['../db/d88/structcvflann_1_1simpleDistance_3_01HellingerDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20l2_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; L2&lt; ElementType &gt;, ElementType &gt;',['../dc/d3c/structcvflann_1_1simpleDistance_3_01L2_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20l2_5fsimple_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; L2_Simple&lt; ElementType &gt;, ElementType &gt;',['../d5/da0/structcvflann_1_1simpleDistance_3_01L2__Simple_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20minkowskidistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; MinkowskiDistance&lt; ElementType &gt;, ElementType &gt;',['../db/dd1/structcvflann_1_1simpleDistance_3_01MinkowskiDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simulatedannealingsolversystem',['SimulatedAnnealingSolverSystem',['../dc/db4/structcv_1_1ml_1_1SimulatedAnnealingSolverSystem.html',1,'cv::ml']]],
  ['singlepolicy',['SinglePolicy',['../de/d31/classcvflann_1_1anyimpl_1_1SinglePolicy.html',1,'cvflann::anyimpl']]],
  ['size',['Size',['../d7/d3e/classcv_1_1gapi_1_1own_1_1Size.html',1,'cv::gapi::own']]],
  ['size_5f',['Size_',['../d6/d50/classcv_1_1Size__.html',1,'cv']]],
  ['size_5f_3c_20float_20_3e',['Size_&lt; float &gt;',['../d6/d50/classcv_1_1Size__.html',1,'cv']]],
  ['sl2',['SL2',['../d5/d46/structcv_1_1SL2.html',1,'cv']]],
  ['slicelayer',['SliceLayer',['../de/d61/classcv_1_1dnn_1_1SliceLayer.html',1,'cv::dnn']]],
  ['softdouble',['softdouble',['../de/df1/structcv_1_1softdouble.html',1,'cv']]],
  ['softfloat',['softfloat',['../d7/d2f/structcv_1_1softfloat.html',1,'cv']]],
  ['softmaxlayer',['SoftmaxLayer',['../d8/d18/classcv_1_1dnn_1_1SoftmaxLayer.html',1,'cv::dnn']]],
  ['sparsemat',['SparseMat',['../dd/da9/classcv_1_1SparseMat.html',1,'cv']]],
  ['sparsemat_5f',['SparseMat_',['../d7/d8a/classcv_1_1SparseMat__.html',1,'cv']]],
  ['sparsematconstiterator',['SparseMatConstIterator',['../df/dec/classcv_1_1SparseMatConstIterator.html',1,'cv']]],
  ['sparsematconstiterator_5f',['SparseMatConstIterator_',['../d9/d29/classcv_1_1SparseMatConstIterator__.html',1,'cv']]],
  ['sparsematiterator',['SparseMatIterator',['../d5/d9b/classcv_1_1SparseMatIterator.html',1,'cv']]],
  ['sparsematiterator_5f',['SparseMatIterator_',['../d3/d24/classcv_1_1SparseMatIterator__.html',1,'cv']]],
  ['sparseopticalflow',['SparseOpticalFlow',['../de/d14/classcv_1_1SparseOpticalFlow.html',1,'cv']]],
  ['sparsepyrlkopticalflow',['SparsePyrLKOpticalFlow',['../d7/d08/classcv_1_1SparsePyrLKOpticalFlow.html',1,'cv']]],
  ['sphericalportraitprojector',['SphericalPortraitProjector',['../d3/d0d/structcv_1_1detail_1_1SphericalPortraitProjector.html',1,'cv::detail']]],
  ['sphericalportraitwarper',['SphericalPortraitWarper',['../d8/d70/classcv_1_1detail_1_1SphericalPortraitWarper.html',1,'cv::detail']]],
  ['sphericalprojector',['SphericalProjector',['../d0/d88/structcv_1_1detail_1_1SphericalProjector.html',1,'cv::detail']]],
  ['sphericalwarper',['SphericalWarper',['../d3/d3c/classcv_1_1SphericalWarper.html',1,'cv']]],
  ['sphericalwarper',['SphericalWarper',['../d6/dd0/classcv_1_1detail_1_1SphericalWarper.html',1,'cv::detail']]],
  ['sphericalwarpergpu',['SphericalWarperGpu',['../db/d09/classcv_1_1detail_1_1SphericalWarperGpu.html',1,'cv::detail']]],
  ['split',['Split',['../d9/d37/classcv_1_1ml_1_1DTrees_1_1Split.html',1,'cv::ml::DTrees']]],
  ['splitlayer',['SplitLayer',['../dd/df9/classcv_1_1dnn_1_1SplitLayer.html',1,'cv::dnn']]],
  ['squaredistance',['squareDistance',['../dc/d68/structcvflann_1_1squareDistance.html',1,'cvflann']]],
  ['squaredistance_3c_20chisquaredistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; ChiSquareDistance&lt; ElementType &gt;, ElementType &gt;',['../d2/deb/structcvflann_1_1squareDistance_3_01ChiSquareDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20hellingerdistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; HellingerDistance&lt; ElementType &gt;, ElementType &gt;',['../dc/d3f/structcvflann_1_1squareDistance_3_01HellingerDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20l2_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; L2&lt; ElementType &gt;, ElementType &gt;',['../d8/db8/structcvflann_1_1squareDistance_3_01L2_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20l2_5fsimple_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; L2_Simple&lt; ElementType &gt;, ElementType &gt;',['../d3/d86/structcvflann_1_1squareDistance_3_01L2__Simple_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20minkowskidistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; MinkowskiDistance&lt; ElementType &gt;, ElementType &gt;',['../dc/d73/structcvflann_1_1squareDistance_3_01MinkowskiDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['startstoptimer',['StartStopTimer',['../de/dd0/classcvflann_1_1StartStopTimer.html',1,'cvflann']]],
  ['statmodel',['StatModel',['../db/d7d/classcv_1_1ml_1_1StatModel.html',1,'cv::ml']]],
  ['stereobm',['StereoBM',['../d9/dba/classcv_1_1StereoBM.html',1,'cv']]],
  ['stereographicprojector',['StereographicProjector',['../d0/ddf/structcv_1_1detail_1_1StereographicProjector.html',1,'cv::detail']]],
  ['stereographicwarper',['StereographicWarper',['../d1/d3d/classcv_1_1detail_1_1StereographicWarper.html',1,'cv::detail']]],
  ['stereographicwarper',['StereographicWarper',['../d2/d5e/classcv_1_1StereographicWarper.html',1,'cv']]],
  ['stereomatcher',['StereoMatcher',['../d2/d6e/classcv_1_1StereoMatcher.html',1,'cv']]],
  ['stereosgbm',['StereoSGBM',['../d2/d85/classcv_1_1StereoSGBM.html',1,'cv']]],
  ['stitcher',['Stitcher',['../d2/d8d/classcv_1_1Stitcher.html',1,'cv']]],
  ['subdiv2d',['Subdiv2D',['../df/dbf/classcv_1_1Subdiv2D.html',1,'cv']]],
  ['svd',['SVD',['../df/df7/classcv_1_1SVD.html',1,'cv']]],
  ['svm',['SVM',['../d1/d2d/classcv_1_1ml_1_1SVM.html',1,'cv::ml']]],
  ['svmsgd',['SVMSGD',['../de/d54/classcv_1_1ml_1_1SVMSGD.html',1,'cv::ml']]]
];
