var searchData=
[
  ['paddinglayer',['PaddingLayer',['../d4/db2/classcv_1_1dnn_1_1PaddingLayer.html',1,'cv::dnn']]],
  ['pairwiseseamfinder',['PairwiseSeamFinder',['../dd/d00/classcv_1_1detail_1_1PairwiseSeamFinder.html',1,'cv::detail']]],
  ['paniniportraitprojector',['PaniniPortraitProjector',['../d3/dd1/structcv_1_1detail_1_1PaniniPortraitProjector.html',1,'cv::detail']]],
  ['paniniportraitwarper',['PaniniPortraitWarper',['../db/dad/classcv_1_1detail_1_1PaniniPortraitWarper.html',1,'cv::detail']]],
  ['paniniportraitwarper',['PaniniPortraitWarper',['../d0/d8b/classcv_1_1PaniniPortraitWarper.html',1,'cv']]],
  ['paniniprojector',['PaniniProjector',['../d2/df1/structcv_1_1detail_1_1PaniniProjector.html',1,'cv::detail']]],
  ['paniniwarper',['PaniniWarper',['../dd/db0/classcv_1_1PaniniWarper.html',1,'cv']]],
  ['paniniwarper',['PaniniWarper',['../db/ddd/classcv_1_1detail_1_1PaniniWarper.html',1,'cv::detail']]],
  ['parallelloopbody',['ParallelLoopBody',['../d2/d74/classcv_1_1ParallelLoopBody.html',1,'cv']]],
  ['parallelloopbodylambdawrapper',['ParallelLoopBodyLambdaWrapper',['../d3/d78/classcv_1_1ParallelLoopBodyLambdaWrapper.html',1,'cv']]],
  ['parameters',['Parameters',['../d4/d80/structcv_1_1DetectionBasedTracker_1_1Parameters.html',1,'cv::DetectionBasedTracker']]],
  ['paramgrid',['ParamGrid',['../d6/dca/classcv_1_1ml_1_1ParamGrid.html',1,'cv::ml']]],
  ['params',['Params',['../d8/da7/structcv_1_1SimpleBlobDetector_1_1Params.html',1,'cv::SimpleBlobDetector']]],
  ['paramtype',['ParamType',['../dd/d77/structcv_1_1ParamType.html',1,'cv']]],
  ['paramtype_3c_20_5ftp_2c_20typename_20std_3a_3aenable_5fif_3c_20std_3a_3ais_5fenum_3c_20_5ftp_20_3e_3a_3avalue_20_3e_3a_3atype_20_3e',['ParamType&lt; _Tp, typename std::enable_if&lt; std::is_enum&lt; _Tp &gt;::value &gt;::type &gt;',['../db/d0d/structcv_1_1ParamType_3_01__Tp_00_01typename_01std_1_1enable__if_3_01std_1_1is__enum_3_01__Tp_01_4_1_1value_01_4_1_1type_01_4.html',1,'cv']]],
  ['paramtype_3c_20algorithm_20_3e',['ParamType&lt; Algorithm &gt;',['../d2/d39/structcv_1_1ParamType_3_01Algorithm_01_4.html',1,'cv']]],
  ['paramtype_3c_20bool_20_3e',['ParamType&lt; bool &gt;',['../d1/d87/structcv_1_1ParamType_3_01bool_01_4.html',1,'cv']]],
  ['paramtype_3c_20double_20_3e',['ParamType&lt; double &gt;',['../d4/d98/structcv_1_1ParamType_3_01double_01_4.html',1,'cv']]],
  ['paramtype_3c_20float_20_3e',['ParamType&lt; float &gt;',['../dd/df2/structcv_1_1ParamType_3_01float_01_4.html',1,'cv']]],
  ['paramtype_3c_20mat_20_3e',['ParamType&lt; Mat &gt;',['../db/d5f/structcv_1_1ParamType_3_01Mat_01_4.html',1,'cv']]],
  ['paramtype_3c_20scalar_20_3e',['ParamType&lt; Scalar &gt;',['../d2/dda/structcv_1_1ParamType_3_01Scalar_01_4.html',1,'cv']]],
  ['paramtype_3c_20std_3a_3avector_3c_20mat_20_3e_20_3e',['ParamType&lt; std::vector&lt; Mat &gt; &gt;',['../dc/d1c/structcv_1_1ParamType_3_01std_1_1vector_3_01Mat_01_4_01_4.html',1,'cv']]],
  ['paramtype_3c_20string_20_3e',['ParamType&lt; String &gt;',['../d0/d5f/structcv_1_1ParamType_3_01String_01_4.html',1,'cv']]],
  ['paramtype_3c_20uchar_20_3e',['ParamType&lt; uchar &gt;',['../d3/da3/structcv_1_1ParamType_3_01uchar_01_4.html',1,'cv']]],
  ['paramtype_3c_20uint64_20_3e',['ParamType&lt; uint64 &gt;',['../dc/d63/structcv_1_1ParamType_3_01uint64_01_4.html',1,'cv']]],
  ['paramtype_3c_20unsigned_20_3e',['ParamType&lt; unsigned &gt;',['../d7/d68/structcv_1_1ParamType_3_01unsigned_01_4.html',1,'cv']]],
  ['pca',['PCA',['../d3/d8d/classcv_1_1PCA.html',1,'cv']]],
  ['permutelayer',['PermuteLayer',['../d2/d3c/classcv_1_1dnn_1_1PermuteLayer.html',1,'cv::dnn']]],
  ['planeportraitprojector',['PlanePortraitProjector',['../df/d0d/structcv_1_1detail_1_1PlanePortraitProjector.html',1,'cv::detail']]],
  ['planeportraitwarper',['PlanePortraitWarper',['../d9/d77/classcv_1_1detail_1_1PlanePortraitWarper.html',1,'cv::detail']]],
  ['planeprojector',['PlaneProjector',['../d6/d1f/structcv_1_1detail_1_1PlaneProjector.html',1,'cv::detail']]],
  ['planewarper',['PlaneWarper',['../d3/d3d/classcv_1_1detail_1_1PlaneWarper.html',1,'cv::detail']]],
  ['planewarper',['PlaneWarper',['../d0/d57/classcv_1_1PlaneWarper.html',1,'cv']]],
  ['planewarpergpu',['PlaneWarperGpu',['../d2/d1a/classcv_1_1detail_1_1PlaneWarperGpu.html',1,'cv::detail']]],
  ['platform',['Platform',['../d8/d87/classcv_1_1ocl_1_1Platform.html',1,'cv::ocl']]],
  ['platforminfo',['PlatformInfo',['../d6/d94/classcv_1_1ocl_1_1PlatformInfo.html',1,'cv::ocl']]],
  ['point',['Point',['../d4/dd6/classcv_1_1gapi_1_1own_1_1Point.html',1,'cv::gapi::own']]],
  ['point3_5f',['Point3_',['../df/d6c/classcv_1_1Point3__.html',1,'cv']]],
  ['point_5f',['Point_',['../db/d4e/classcv_1_1Point__.html',1,'cv']]],
  ['point_5f_3c_20float_20_3e',['Point_&lt; float &gt;',['../db/d4e/classcv_1_1Point__.html',1,'cv']]],
  ['pooledallocator',['PooledAllocator',['../d9/d03/classcvflann_1_1PooledAllocator.html',1,'cvflann']]],
  ['poolinglayer',['PoolingLayer',['../de/d7d/classcv_1_1dnn_1_1PoolingLayer.html',1,'cv::dnn']]],
  ['powerlayer',['PowerLayer',['../d2/da0/classcv_1_1dnn_1_1PowerLayer.html',1,'cv::dnn']]],
  ['priorboxlayer',['PriorBoxLayer',['../da/d1e/classcv_1_1dnn_1_1PriorBoxLayer.html',1,'cv::dnn']]],
  ['program',['Program',['../d2/d88/classcv_1_1ocl_1_1Program.html',1,'cv::ocl']]],
  ['programsource',['ProgramSource',['../d5/de3/classcv_1_1ocl_1_1ProgramSource.html',1,'cv::ocl']]],
  ['projectorbase',['ProjectorBase',['../dc/d2c/structcv_1_1detail_1_1ProjectorBase.html',1,'cv::detail']]],
  ['proposallayer',['ProposalLayer',['../da/d6b/classcv_1_1dnn_1_1ProposalLayer.html',1,'cv::dnn']]],
  ['prototometa',['ProtoToMeta',['../dd/ddb/structcv_1_1detail_1_1ProtoToMeta.html',1,'cv::detail']]],
  ['prototometa_3c_20cv_3a_3agarray_3c_20u_20_3e_20_3e',['ProtoToMeta&lt; cv::GArray&lt; U &gt; &gt;',['../dd/d51/structcv_1_1detail_1_1ProtoToMeta_3_01cv_1_1GArray_3_01U_01_4_01_4.html',1,'cv::detail']]],
  ['prototometa_3c_20cv_3a_3agmat_20_3e',['ProtoToMeta&lt; cv::GMat &gt;',['../d0/d99/structcv_1_1detail_1_1ProtoToMeta_3_01cv_1_1GMat_01_4.html',1,'cv::detail']]],
  ['prototometa_3c_20cv_3a_3agscalar_20_3e',['ProtoToMeta&lt; cv::GScalar &gt;',['../df/d8b/structcv_1_1detail_1_1ProtoToMeta_3_01cv_1_1GScalar_01_4.html',1,'cv::detail']]],
  ['prototoparam',['ProtoToParam',['../dd/dc5/structcv_1_1detail_1_1ProtoToParam.html',1,'cv::detail']]],
  ['prototoparam_3c_20cv_3a_3agarray_3c_20u_20_3e_20_3e',['ProtoToParam&lt; cv::GArray&lt; U &gt; &gt;',['../d5/d57/structcv_1_1detail_1_1ProtoToParam_3_01cv_1_1GArray_3_01U_01_4_01_4.html',1,'cv::detail']]],
  ['prototoparam_3c_20cv_3a_3agmat_20_3e',['ProtoToParam&lt; cv::GMat &gt;',['../dc/dc8/structcv_1_1detail_1_1ProtoToParam_3_01cv_1_1GMat_01_4.html',1,'cv::detail']]],
  ['prototoparam_3c_20cv_3a_3agscalar_20_3e',['ProtoToParam&lt; cv::GScalar &gt;',['../de/d65/structcv_1_1detail_1_1ProtoToParam_3_01cv_1_1GScalar_01_4.html',1,'cv::detail']]],
  ['pyrotationwarper',['PyRotationWarper',['../d5/d76/classcv_1_1PyRotationWarper.html',1,'cv']]]
];
