var searchData=
[
  ['datadepth',['DataDepth',['../d7/d0e/classcv_1_1DataDepth.html',1,'cv']]],
  ['datatype',['Datatype',['../d4/dbd/structcvflann_1_1Datatype.html',1,'cvflann']]],
  ['datatype',['DataType',['../d0/d3a/classcv_1_1DataType.html',1,'cv']]],
  ['datatype_3c_20char_20_3e',['Datatype&lt; char &gt;',['../d3/df4/structcvflann_1_1Datatype_3_01char_01_4.html',1,'cvflann']]],
  ['datatype_3c_20double_20_3e',['Datatype&lt; double &gt;',['../d2/d8d/structcvflann_1_1Datatype_3_01double_01_4.html',1,'cvflann']]],
  ['datatype_3c_20float_20_3e',['Datatype&lt; float &gt;',['../dd/d42/structcvflann_1_1Datatype_3_01float_01_4.html',1,'cvflann']]],
  ['datatype_3c_20short_20_3e',['Datatype&lt; short &gt;',['../db/de5/structcvflann_1_1Datatype_3_01short_01_4.html',1,'cvflann']]],
  ['datatype_3c_20unsigned_20char_20_3e',['Datatype&lt; unsigned char &gt;',['../d3/dea/structcvflann_1_1Datatype_3_01unsigned_01char_01_4.html',1,'cvflann']]],
  ['datatype_3c_20unsigned_20short_20_3e',['Datatype&lt; unsigned short &gt;',['../dc/dbe/structcvflann_1_1Datatype_3_01unsigned_01short_01_4.html',1,'cvflann']]],
  ['dct2d',['DCT2D',['../d5/d57/structcv_1_1hal_1_1DCT2D.html',1,'cv::hal']]],
  ['deconvolutionlayer',['DeconvolutionLayer',['../dd/d77/classcv_1_1dnn_1_1DeconvolutionLayer.html',1,'cv::dnn']]],
  ['defaultdeleter_3c_20cvcapture_20_3e',['DefaultDeleter&lt; CvCapture &gt;',['../d0/d90/structcv_1_1DefaultDeleter_3_01CvCapture_01_4.html',1,'cv']]],
  ['defaultdeleter_3c_20cvhaarclassifiercascade_20_3e',['DefaultDeleter&lt; CvHaarClassifierCascade &gt;',['../d9/ddf/structcv_1_1DefaultDeleter_3_01CvHaarClassifierCascade_01_4.html',1,'cv']]],
  ['defaultdeleter_3c_20cvvideowriter_20_3e',['DefaultDeleter&lt; CvVideoWriter &gt;',['../d2/d37/structcv_1_1DefaultDeleter_3_01CvVideoWriter_01_4.html',1,'cv']]],
  ['denseopticalflow',['DenseOpticalFlow',['../df/dde/classcv_1_1DenseOpticalFlow.html',1,'cv']]],
  ['descriptorcollection',['DescriptorCollection',['../d4/dac/classcv_1_1DescriptorMatcher_1_1DescriptorCollection.html',1,'cv::DescriptorMatcher']]],
  ['descriptormatcher',['DescriptorMatcher',['../db/d39/classcv_1_1DescriptorMatcher.html',1,'cv']]],
  ['detectionbasedtracker',['DetectionBasedTracker',['../db/de9/classcv_1_1DetectionBasedTracker.html',1,'cv']]],
  ['detectionmodel',['DetectionModel',['../d3/df1/classcv_1_1dnn_1_1DetectionModel.html',1,'cv::dnn']]],
  ['detectionoutputlayer',['DetectionOutputLayer',['../da/dbd/classcv_1_1dnn_1_1DetectionOutputLayer.html',1,'cv::dnn']]],
  ['detectionroi',['DetectionROI',['../d3/d34/structcv_1_1DetectionROI.html',1,'cv']]],
  ['device',['Device',['../d7/d9f/classcv_1_1ocl_1_1Device.html',1,'cv::ocl']]],
  ['dft1d',['DFT1D',['../d8/d03/structcv_1_1hal_1_1DFT1D.html',1,'cv::hal']]],
  ['dft2d',['DFT2D',['../d6/d77/structcv_1_1hal_1_1DFT2D.html',1,'cv::hal']]],
  ['dict',['Dict',['../d9/d2b/classcv_1_1dnn_1_1Dict.html',1,'cv::dnn']]],
  ['dictvalue',['DictValue',['../d4/db3/structcv_1_1dnn_1_1DictValue.html',1,'cv::dnn']]],
  ['disjointsets',['DisjointSets',['../dc/d3e/classcv_1_1detail_1_1DisjointSets.html',1,'cv::detail']]],
  ['disopticalflow',['DISOpticalFlow',['../de/d4f/classcv_1_1DISOpticalFlow.html',1,'cv']]],
  ['distindex',['DistIndex',['../d0/d28/structcvflann_1_1UniqueResultSet_1_1DistIndex.html',1,'cvflann::UniqueResultSet']]],
  ['dmatch',['DMatch',['../d4/de0/classcv_1_1DMatch.html',1,'cv']]],
  ['downhillsolver',['DownhillSolver',['../d4/d43/classcv_1_1DownhillSolver.html',1,'cv']]],
  ['dpseamfinder',['DpSeamFinder',['../d0/dd5/classcv_1_1detail_1_1DpSeamFinder.html',1,'cv::detail']]],
  ['dtrees',['DTrees',['../d8/d89/classcv_1_1ml_1_1DTrees.html',1,'cv::ml']]],
  ['dynamicbitset',['DynamicBitset',['../d1/d73/classcvflann_1_1DynamicBitset.html',1,'cvflann']]]
];
