var searchData=
[
  ['o4a_5fsdk_2emarkdown',['O4A_SDK.markdown',['../dc/d7c/O4A__SDK_8markdown.html',1,'']]],
  ['objdetect_2ehpp',['objdetect.hpp',['../d7/df0/objdetect_2objdetect_8hpp.html',1,'']]],
  ['objdetect_2ehpp',['objdetect.hpp',['../d8/da3/objdetect_8hpp.html',1,'']]],
  ['object_5ffactory_2eh',['object_factory.h',['../de/d9f/object__factory_8h.html',1,'']]],
  ['ocl_2ehpp',['ocl.hpp',['../da/d74/ocl_8hpp.html',1,'']]],
  ['ocl_5fdefs_2ehpp',['ocl_defs.hpp',['../d1/d08/ocl__defs_8hpp.html',1,'']]],
  ['ocl_5fgenbase_2ehpp',['ocl_genbase.hpp',['../d1/d1f/ocl__genbase_8hpp.html',1,'']]],
  ['opencl_5finfo_2ehpp',['opencl_info.hpp',['../d6/d54/opencl__info_8hpp.html',1,'']]],
  ['opencl_5fsvm_2ehpp',['opencl_svm.hpp',['../df/d48/opencl__svm_8hpp.html',1,'']]],
  ['opencv_5fincludes_2ehpp',['opencv_includes.hpp',['../dc/d17/opencv__includes_8hpp.html',1,'']]],
  ['opengl_2ehpp',['opengl.hpp',['../d4/db0/opengl_8hpp.html',1,'']]],
  ['opening_5fclosing_5fhats_2emarkdown',['opening_closing_hats.markdown',['../dd/d42/opening__closing__hats_8markdown.html',1,'']]],
  ['operations_2ehpp',['operations.hpp',['../d6/d00/operations_8hpp.html',1,'']]],
  ['operators_2ehpp',['operators.hpp',['../dd/dcd/operators_8hpp.html',1,'']]],
  ['optical_5fflow_2emarkdown',['optical_flow.markdown',['../db/d50/optical__flow_8markdown.html',1,'']]],
  ['optim_2ehpp',['optim.hpp',['../d3/d46/optim_8hpp.html',1,'']]],
  ['optional_2ehpp',['optional.hpp',['../db/dd5/optional_8hpp.html',1,'']]],
  ['out_5fof_5ffocus_5fdeblur_5ffilter_2emarkdown',['out_of_focus_deblur_filter.markdown',['../d4/d4d/out__of__focus__deblur__filter_8markdown.html',1,'']]],
  ['ovx_2ehpp',['ovx.hpp',['../dd/ded/ovx_8hpp.html',1,'']]],
  ['ovx_5fdefs_2ehpp',['ovx_defs.hpp',['../de/d03/ovx__defs_8hpp.html',1,'']]]
];
