var searchData=
[
  ['high_2dlevel_20design_20overview',['High-level design overview',['../gapi_hld.html',1,'gapi']]],
  ['how_20to_20use_20background_20subtraction_20methods',['How to Use Background Subtraction Methods',['../tutorial_background_subtraction.html',1,'tutorial_table_of_content_video']]],
  ['how_20to_20run_20deep_20networks_20on_20android_20device',['How to run deep networks on Android device',['../tutorial_dnn_android.html',1,'tutorial_table_of_content_dnn']]],
  ['how_20to_20enable_20halide_20backend_20for_20improve_20efficiency',['How to enable Halide backend for improve efficiency',['../tutorial_dnn_halide.html',1,'tutorial_table_of_content_dnn']]],
  ['how_20to_20schedule_20your_20network_20for_20halide_20backend',['How to schedule your network for Halide backend',['../tutorial_dnn_halide_scheduling.html',1,'tutorial_table_of_content_dnn']]],
  ['how_20to_20run_20deep_20networks_20in_20browser',['How to run deep networks in browser',['../tutorial_dnn_javascript.html',1,'tutorial_table_of_content_dnn']]],
  ['harris_20corner_20detector',['Harris corner detector',['../tutorial_harris_detector.html',1,'tutorial_table_of_content_features2d']]],
  ['high_20dynamic_20range_20imaging',['High Dynamic Range Imaging',['../tutorial_hdr_imaging.html',1,'tutorial_table_of_content_photo']]],
  ['histogram_20calculation',['Histogram Calculation',['../tutorial_histogram_calculation.html',1,'tutorial_table_of_content_imgproc']]],
  ['histogram_20comparison',['Histogram Comparison',['../tutorial_histogram_comparison.html',1,'tutorial_table_of_content_imgproc']]],
  ['histogram_20equalization',['Histogram Equalization',['../tutorial_histogram_equalization.html',1,'tutorial_table_of_content_imgproc']]],
  ['hit_2dor_2dmiss',['Hit-or-Miss',['../tutorial_hitOrMiss.html',1,'tutorial_table_of_content_imgproc']]],
  ['hough_20circle_20transform',['Hough Circle Transform',['../tutorial_hough_circle.html',1,'tutorial_table_of_content_imgproc']]],
  ['hough_20line_20transform',['Hough Line Transform',['../tutorial_hough_lines.html',1,'tutorial_table_of_content_imgproc']]],
  ['how_20to_20scan_20images_2c_20lookup_20tables_20and_20time_20measurement_20with_20opencv',['How to scan images, lookup tables and time measurement with OpenCV',['../tutorial_how_to_scan_images.html',1,'tutorial_table_of_content_core']]],
  ['how_20to_20use_20the_20opencv_20parallel_5ffor_5f_20to_20parallelize_20your_20code',['How to use the OpenCV parallel_for_ to parallelize your code',['../tutorial_how_to_use_OpenCV_parallel_for_.html',1,'tutorial_table_of_content_core']]],
  ['histogram_20_2d_203_20_3a_20histogram_20backprojection',['Histogram - 3 : Histogram Backprojection',['../tutorial_js_histogram_backprojection.html',1,'tutorial_js_table_of_contents_histograms']]],
  ['histograms_20_2d_201_20_3a_20find_2c_20plot_2c_20analyze_20_21_21_21',['Histograms - 1 : Find, Plot, Analyze !!!',['../tutorial_js_histogram_begins.html',1,'tutorial_js_table_of_contents_histograms']]],
  ['histograms_20_2d_202_3a_20histogram_20equalization',['Histograms - 2: Histogram Equalization',['../tutorial_js_histogram_equalization.html',1,'tutorial_js_table_of_contents_histograms']]],
  ['hough_20circle_20transform',['Hough Circle Transform',['../tutorial_js_houghcircles.html',1,'tutorial_js_table_of_contents_imgproc']]],
  ['hough_20line_20transform',['Hough Line Transform',['../tutorial_js_houghlines.html',1,'tutorial_js_table_of_contents_imgproc']]],
  ['histograms_20in_20opencv_2ejs',['Histograms in OpenCV.js',['../tutorial_js_table_of_contents_histograms.html',1,'tutorial_js_table_of_contents_imgproc']]],
  ['histograms_20_2d_203_20_3a_202d_20histograms',['Histograms - 3 : 2D Histograms',['../tutorial_py_2d_histogram.html',1,'tutorial_py_table_of_contents_histograms']]],
  ['how_20opencv_2dpython_20bindings_20works_3f',['How OpenCV-Python Bindings Works?',['../tutorial_py_bindings_basics.html',1,'tutorial_py_table_of_contents_bindings']]],
  ['harris_20corner_20detection',['Harris Corner Detection',['../tutorial_py_features_harris.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['high_20dynamic_20range_20_28hdr_29',['High Dynamic Range (HDR)',['../tutorial_py_hdr.html',1,'tutorial_py_table_of_contents_photo']]],
  ['histogram_20_2d_204_20_3a_20histogram_20backprojection',['Histogram - 4 : Histogram Backprojection',['../tutorial_py_histogram_backprojection.html',1,'tutorial_py_table_of_contents_histograms']]],
  ['histograms_20_2d_201_20_3a_20find_2c_20plot_2c_20analyze_20_21_21_21',['Histograms - 1 : Find, Plot, Analyze !!!',['../tutorial_py_histogram_begins.html',1,'tutorial_py_table_of_contents_histograms']]],
  ['histograms_20_2d_202_3a_20histogram_20equalization',['Histograms - 2: Histogram Equalization',['../tutorial_py_histogram_equalization.html',1,'tutorial_py_table_of_contents_histograms']]],
  ['hough_20circle_20transform',['Hough Circle Transform',['../tutorial_py_houghcircles.html',1,'tutorial_py_table_of_contents_imgproc']]],
  ['hough_20line_20transform',['Hough Line Transform',['../tutorial_py_houghlines.html',1,'tutorial_py_table_of_contents_imgproc']]],
  ['histograms_20in_20opencv',['Histograms in OpenCV',['../tutorial_py_table_of_contents_histograms.html',1,'tutorial_py_table_of_contents_imgproc']]],
  ['high_20level_20stitching_20api_20_28stitcher_20class_29',['High level stitching API (Stitcher class)',['../tutorial_stitcher.html',1,'tutorial_table_of_content_stitching']]],
  ['high_20level_20gui_20and_20media_20_28highgui_20module_29',['High Level GUI and Media (highgui module)',['../tutorial_table_of_content_highgui.html',1,'tutorial_root']]],
  ['how_20to_20build_20applications_20with_20opencv_20inside_20the_20_22microsoft_20visual_20studio_22',['How to build applications with OpenCV inside the &quot;Microsoft Visual Studio&quot;',['../tutorial_windows_visual_studio_opencv.html',1,'tutorial_table_of_content_introduction']]]
];
