var searchData=
[
  ['cuda_20module_20introduction',['CUDA Module Introduction',['../cuda_intro.html',1,'']]],
  ['color_20conversions',['Color conversions',['../imgproc_color_conversions.html',1,'']]],
  ['cross_20compilation_20for_20arm_20based_20linux_20systems',['Cross compilation for ARM based Linux systems',['../tutorial_arm_crosscompile_with_cmake.html',1,'tutorial_table_of_content_introduction']]],
  ['changing_20the_20contrast_20and_20brightness_20of_20an_20image_21',['Changing the contrast and brightness of an image!',['../tutorial_basic_linear_transform.html',1,'tutorial_table_of_content_core']]],
  ['creating_20bounding_20boxes_20and_20circles_20for_20contours',['Creating Bounding boxes and circles for contours',['../tutorial_bounding_rects_circles.html',1,'tutorial_table_of_content_imgproc']]],
  ['creating_20bounding_20rotated_20boxes_20and_20ellipses_20for_20contours',['Creating Bounding rotated boxes and ellipses for contours',['../tutorial_bounding_rotated_ellipses.html',1,'tutorial_table_of_content_imgproc']]],
  ['camera_20calibration_20with_20opencv',['Camera calibration With OpenCV',['../tutorial_camera_calibration.html',1,'tutorial_table_of_content_calib3d']]],
  ['create_20calibration_20pattern',['Create calibration pattern',['../tutorial_camera_calibration_pattern.html',1,'tutorial_table_of_content_calib3d']]],
  ['camera_20calibration_20with_20square_20chessboard',['Camera calibration with square chessboard',['../tutorial_camera_calibration_square_chess.html',1,'tutorial_table_of_content_calib3d']]],
  ['canny_20edge_20detector',['Canny Edge Detector',['../tutorial_canny_detector.html',1,'tutorial_table_of_content_imgproc']]],
  ['cascade_20classifier',['Cascade Classifier',['../tutorial_cascade_classifier.html',1,'tutorial_table_of_content_objdetect']]],
  ['cross_20referencing_20opencv_20from_20other_20doxygen_20projects',['Cross referencing OpenCV from other Doxygen projects',['../tutorial_cross_referencing.html',1,'tutorial_table_of_content_introduction']]],
  ['custom_20deep_20learning_20layers_20support',['Custom deep learning layers support',['../tutorial_dnn_custom_layers.html',1,'tutorial_table_of_content_dnn']]],
  ['creating_20your_20own_20corner_20detector',['Creating your own corner detector',['../tutorial_generic_corner_detector.html',1,'tutorial_table_of_content_features2d']]],
  ['convex_20hull',['Convex Hull',['../tutorial_hull.html',1,'tutorial_table_of_content_imgproc']]],
  ['canny_20edge_20detection',['Canny Edge Detection',['../tutorial_js_canny.html',1,'tutorial_js_table_of_contents_imgproc']]],
  ['changing_20colorspaces',['Changing Colorspaces',['../tutorial_js_colorspaces.html',1,'tutorial_js_table_of_contents_imgproc']]],
  ['contour_20features',['Contour Features',['../tutorial_js_contour_features.html',1,'tutorial_js_table_of_contents_contours']]],
  ['contour_20properties',['Contour Properties',['../tutorial_js_contour_properties.html',1,'tutorial_js_table_of_contents_contours']]],
  ['contours_20_3a_20getting_20started',['Contours : Getting Started',['../tutorial_js_contours_begin.html',1,'tutorial_js_table_of_contents_contours']]],
  ['contours_20hierarchy',['Contours Hierarchy',['../tutorial_js_contours_hierarchy.html',1,'tutorial_js_table_of_contents_contours']]],
  ['contours_20_3a_20more_20functions',['Contours : More Functions',['../tutorial_js_contours_more_functions.html',1,'tutorial_js_table_of_contents_contours']]],
  ['contours_20in_20opencv_2ejs',['Contours in OpenCV.js',['../tutorial_js_table_of_contents_contours.html',1,'tutorial_js_table_of_contents_imgproc']]],
  ['core_20operations',['Core Operations',['../tutorial_js_table_of_contents_core.html',1,'tutorial_js_root']]],
  ['camera_20calibration',['Camera Calibration',['../tutorial_py_calibration.html',1,'tutorial_py_table_of_contents_calib3d']]],
  ['canny_20edge_20detection',['Canny Edge Detection',['../tutorial_py_canny.html',1,'tutorial_py_table_of_contents_imgproc']]],
  ['changing_20colorspaces',['Changing Colorspaces',['../tutorial_py_colorspaces.html',1,'tutorial_py_table_of_contents_imgproc']]],
  ['contour_20features',['Contour Features',['../tutorial_py_contour_features.html',1,'tutorial_py_table_of_contents_contours']]],
  ['contour_20properties',['Contour Properties',['../tutorial_py_contour_properties.html',1,'tutorial_py_table_of_contents_contours']]],
  ['contours_20_3a_20getting_20started',['Contours : Getting Started',['../tutorial_py_contours_begin.html',1,'tutorial_py_table_of_contents_contours']]],
  ['contours_20hierarchy',['Contours Hierarchy',['../tutorial_py_contours_hierarchy.html',1,'tutorial_py_table_of_contents_contours']]],
  ['contours_20_3a_20more_20functions',['Contours : More Functions',['../tutorial_py_contours_more_functions.html',1,'tutorial_py_table_of_contents_contours']]],
  ['camera_20calibration_20and_203d_20reconstruction',['Camera Calibration and 3D Reconstruction',['../tutorial_py_table_of_contents_calib3d.html',1,'tutorial_py_root']]],
  ['contours_20in_20opencv',['Contours in OpenCV',['../tutorial_py_table_of_contents_contours.html',1,'tutorial_py_table_of_contents_imgproc']]],
  ['core_20operations',['Core Operations',['../tutorial_py_table_of_contents_core.html',1,'tutorial_py_root']]],
  ['computational_20photography',['Computational Photography',['../tutorial_py_table_of_contents_photo.html',1,'tutorial_py_root']]],
  ['camera_20calibration_20and_203d_20reconstruction_20_28calib3d_20module_29',['Camera calibration and 3D reconstruction (calib3d module)',['../tutorial_table_of_content_calib3d.html',1,'tutorial_root']]],
  ['computational_20photography_20_28photo_20module_29',['Computational photography (photo module)',['../tutorial_table_of_content_photo.html',1,'tutorial_root']]],
  ['cascade_20classifier_20training',['Cascade Classifier Training',['../tutorial_traincascade.html',1,'tutorial_table_of_content_objdetect']]],
  ['creating_20a_20video_20with_20opencv',['Creating a video with OpenCV',['../tutorial_video_write.html',1,'tutorial_table_of_content_videoio']]]
];
